### ISSUE TITLE
Broken NLFFF Data Calculation and Unit Discrepancy in `01_dl_build_box.ipynb`

### ISSUE THREAD

**Issue by sageyu123** [vit1-irk/pyAMPP-0#1]
In the notebook [`01_dl_build_box.ipynb`](https://github.com/vit1-irk/pyAMPP-0/blob/main/01_dl_build_box.ipynb), the code responsible for calculating NLFFF data is currently broken. The issue stems from the removal of `WWNLFFFReconstruction.so` from Alexey's [Magnetic-Field_Library repository](https://github.com/Alexey-Stupishin/Magnetic-Field_Library).

#### Code Snippet
```python
nlfff_libpath = (Path('./nlfff/binaries/WWNLFFFReconstruction.so').resolve())
maglib = MagFieldWrapper(nlfff_libpath)

dr = (map_field.rsun_obs / map_field.rsun_meters * res_km).value
maglib.load_cube_vars(bx_lff, by_lff, bz_lff, dr)

box = maglib.NLFFF()
energy_new = maglib.energy
print('NLFFF energy:     ' + str(energy_new) + ' erg')

print("Calculating field lines")
lines = maglib.lines(seeds = None)
```

#### Issues Identified
1. **Missing Dependency**:
   - The `WWNLFFFReconstruction.so` library, previously available in Alexey's repository, has been removed. This removal breaks the NLFFF data calculation in the notebook.

2. **Unit Discrepancy**:
   - According to Alexey's code, the last argument of `maglib.load_cube_vars` should be in units of cm. The current notebook implementation uses `arcsec`, which may cause incorrect results.

#### Requested Actions
1. **Dependency Restoration**:
   - Please provide guidance on how to restore or replace the `WWNLFFFReconstruction.so` library to make the code functional again.

2. **Unit Correction**:
   - Confirm the appropriate unit for the last argument in `maglib.load_cube_vars` and update the notebook code accordingly.

Any advice or recommendations to resolve these issues would be greatly appreciated @vit1-irk @Alexey-Stupishin

**Comment by vit1-irk** [comment]
Alexey says he recreated the repository with different structure and provided a Makefile for Linux users to compile the library. I am not really familiar with pip build process, but I think it is possible to compile the library during package installation process. I will check the units, thank you for noticing.

**Comment by vit1-irk** [comment]
```bash
cd nlfff/Linux
make -j5
```

Then in `nlfff/binaries` the file `WWNLFFFReconstruction.so` appears. It works for me with latest g++ 13. We can compile it when pip install somehow. Also, for different architectures compiling the library on user machine may be the best choice.

**Comment by vit1-irk** [comment]
In the latest commit I

1. Fixed the dimensionality issue and provided the correct quantity to NLFFF code
2. Fixed the issue where bottom field boundary of lff was not replaced from the source data

My code can produce correct radio sources now

**Comment by vit1-irk** [comment]
See the ipynb file from latest commit

**Comment by sageyu123** [comment]
Thanks! I will check it out.

Sijie Yu, PhD
Associate Research Professor
Department of Physics/Center for Solar-Terrestrial Research
New Jersey Institute of Technology
https://web.njit.edu/~sjyu/
